### PR TITLE
Enhancement of Lua Code, JSON Minification, and Error Resolution

### PR DESCRIPTION
**Pull request by ghost**
* Lua code has been optimized to improve its efficiency and speed.
* JSON files have been minified, resulting in a significant reduction in file size.
* Syntax errors have been fixed in the code.
* Prerequisites have been added to address some of the common errors that can occur in the Lua code.

### CODE REVIEW

**Comment by jojos38** [comment]
Hey, thanks for your pull request!
I'm not against minifying the code, however the issue is that it makes the code harder to edit to future people who would want to contribute to the project. Especially since I don't know any tool to auto format Jbeam.
How much did you gain in size doing this please?
A nice thing would be to have a tool aside that I can use to minify the code before releasing the mod as a .zip, this way the Git project would stay clean

**Comment by ghost** [comment]
I understand the concern, though I would like to inform you that `jbeam` is actually associated with `cjson` and therefore supports comments, this means that it uses the `cjson` format and can be easily formatted using the basic JSON Language Features formatter available within Visual Studio Code. You can also associate the corresponding vehicle model's meshes by using their names, this is already done in existing `jbeam` files.

The `jbeam` files rely on the vehicle's model and will only work if the name of the object you are changing is available within the model. You can also associate `jbeam` with `cjson`, and `cs` with `torquescript` whenever working on a project like this.

```json
{
    "files.associations": {
        "*.jbeam": "cjson",
        "*.cs": "torquescript"
    }
}
```

**Comment by jojos38** [comment]
I see, thank you for the explanation, I will add this to the readme

**Comment by ghost** [comment]
Any way I can reach you on Discord? I'd like to discuss improving this mod in the future, if that's something you're down to do.

**Comment by jojos38** [comment]
Sure, you can add me jojos38#1337

> Any way I can reach you on Discord? I'd like to discuss improving this mod in the future, if that's something you're down to do.

**Comment by jlnprssnr** [comment]
I mean it's nice that the minified JBeam files save storage, but maybe optimize the configuration preview pictures first? They are >2MB each. Vanilla cars use jpegs of smaller pixel size which are <500kb.

**Pull request merged**
